# /*******************************************************************************
#  * Copyright 2016 -- 2021 IBM Corporation
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
# *******************************************************************************/

# ******************************************************************************
# *
# *                            cloudFPGA
# *
# *-----------------------------------------------------------------------------
# *
# * Title   : Default timing constraint file for this version of the ROLE.
# *
# * File    : roleFlash.xdc
# *
# * Created : Feb. 2018
# * Authors : Francois Abel <fab@zurich.ibm.com>
# *
# * Devices : xcku060-ffva1156-2-i
# * Tools   : Vivado v2017.4 (64-bit)
# * Depends : None
# *
# * Description : This file contains all the timing constraints for synthesizing
# *   the Flash version of the ROLE embedded into the FMKU60 Flash device. These
# *   constraints are defined for the ROLE as if is was a standalone design. 
# *
# *-----------------------------------------------------------------------------
# * Comments:
# *  - According to UG1119-Lab1, "If the created clock is internal to the IP 
# *    (GT), or if the IP contains an input buffer (IBUF), the create_clock 
# *    constraint should stay in the IP XDC file because it is needed to define 
# *    local clocks."
# *
# ******************************************************************************


#=====================================================================
# Main synchronous clock (generated by the SHELL). 
#=====================================================================

create_clock -period 6.400 [ get_ports piSHL_156_25Clk ]

#=====================================================================
# Free USR1 running clock (generated by the TOP). 
#=====================================================================

create_clock -period 4.000 [ get_ports piTOP_250_00Clk ]

